image:
  repository: ghcr.io/carlosmsanchezm/hello-app
  digest: sha256:0afa080be58b4240fa9bff3f23a8b4dcf94a811cfde91e7b57d43180ed1ab010
  pullPolicy: IfNotPresent

# If GHCR is private, set to ["ghcr-creds"] and create that secret once per namespace.
imagePullSecrets: ["ghcr-creds"]

replicaCount: 2

containerPort: 8080
healthzPath: /healthz
httpPortName: http

env:
  MESSAGE: "Hello from your app!"

resources:
  requests: { cpu: 50m,  memory: 64Mi }
  limits:   { cpu: 500m, memory: 256Mi }

service:
  port: 80
  type: ClusterIP

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  dropCaps: ["ALL"]

networkPolicy:
  enabled: true
  allowedSelector: { role: ingress }   # pods allowed to call this app

# HA defaults
pdb:
  enabled: true
  minAvailable: 1